# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSeleniumtest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_seleniumtest1(self):
    # Test name: selenium_test1
    # Step # | name | target | value
    # 1 | open | /index.html | 
    self.driver.get("https://www.ntt.com/index.html")
    # 2 | click | linkText=電子請求を支援する「BConnectionデジタルトレード」、中小企業向けに無料請求書作成アプリの提供とファクタリングサービスの販売取り次ぎを開始 | 
    self.driver.find_element(By.LINK_TEXT, "電子請求を支援する「BConnectionデジタルトレード」、中小企業向けに無料請求書作成アプリの提供とファクタリングサービスの販売取り次ぎを開始").click()
    # 3 | verifyText | css=.grid_cols > h3 | 電子請求を支援する「BConnectionデジタルトレード」、中小企業向けに無料請求書作成アプリの提供とファクタリングサービスの販売取り次ぎを開始
    assert self.driver.find_element(By.CSS_SELECTOR, ".grid_cols > h3").text == "電子請求を支援する「BConnectionデジタルトレード」、中小企業向けに無料請求書作成アプリの提供とファクタリングサービスの販売取り次ぎを開始"
    # 4 | click | css=.global-nav__tab:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".global-nav__tab:nth-child(1)").click()
    # 5 | assertElementPresent | css=.global-drop--active .global-drop__main | 
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".global-drop--active .global-drop__main")
    assert len(elements) > 0
    # 6 | click | xpath=//div[@id='global-nav']/div[2]/div/ul/li[6]/span/span | 
    self.driver.find_element(By.XPATH, "//div[@id=\'global-nav\']/div[2]/div/ul/li[6]/span/span").click()
    # 7 | verifyText | css=.global-drop-nav--active > .global-drop-nav__header > .global-drop-nav__text | 都市に関わる人やモノの情報を集積・分析し、省エネルギー化や防犯をサポート\n安心・安全、サステナブルな都市の実現を支援します
    assert self.driver.find_element(By.CSS_SELECTOR, ".global-drop-nav--active > .global-drop-nav__header > .global-drop-nav__text").text == "都市に関わる人やモノの情報を集積・分析し、省エネルギー化や防犯をサポート\n安心・安全、サステナブルな都市の実現を支援します"
  
